# Generated by Django 4.2.28 on 2026-03-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(choices=[('Lenguaje', 'Lenguaje y Comunicación'), ('Matemáticas', 'Matemáticas'), ('Ciencias', 'Ciencias Naturales'), ('Historia', 'Historia y Geografía'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes Visuales')], max_length=50)),
                ('nota_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nota_2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nota_3', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nota_4', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['alumno', 'asignatura'],
                'unique_together': {('alumno', 'asignatura')},
            },
        ),
    ]
