# Generated by Django 4.2.28 on 2026-03-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(choices=[('Lenguaje', 'Lenguaje y Comunicación'), ('Matemáticas', 'Matemáticas'), ('Ciencias', 'Ciencias Naturales'), ('Historia', 'Historia y Geografía'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes Visuales')], max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], default='Presente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'alumno', 'asignatura'],
                'unique_together': {('alumno', 'asignatura', 'fecha')},
            },
        ),
    ]
