# Generated by Django 6.0.2 on 2026-03-03 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('notas', '0002_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='asignatura',
            field=models.CharField(choices=[('Lenguaje', 'Lenguaje'), ('Matemáticas', 'Matemáticas'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='asignatura',
            field=models.CharField(choices=[('Lenguaje', 'Lenguaje'), ('Matemáticas', 'Matemáticas'), ('Ciencias', 'Ciencias'), ('Historia', 'Historia'), ('Inglés', 'Inglés'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes')], max_length=50),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('academica', '📚 Académica'), ('conductual', '⚠️ Conductual'), ('familiar', '🏠 Familiar'), ('medica', '🏥 Médica')], default='academica', max_length=20)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='alumnos.alumno')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
