# Generated by Django 4.2.29 on 2026-03-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('psicologo', '🧠 Psicólogo/a'), ('fonoaudiologo', '🗣️ Fonoaudiólogo/a'), ('t_ocupacional', '🤝 Terapeuta Ocupacional'), ('prof_diferencial', '📚 Profesor/a Diferencial'), ('asist_social', '👥 Asistente Social')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('dias', models.CharField(help_text='Días separados por coma: lunes,miercoles', max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
        ),
        migrations.CreateModel(
            name='RegistroPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad', models.CharField(choices=[('TEA', '🧩 TEA — Trastorno del Espectro Autista'), ('TDAH', '⚡ TDAH — Déficit Atencional e Hiperactividad'), ('DEA', '📖 DEA — Dificultad Específica del Aprendizaje'), ('DI', '🧠 DI — Discapacidad Intelectual'), ('DL', '🗣️ DL — Dificultad del Lenguaje'), ('DM', '♿ DM — Discapacidad Motora'), ('DV', '👁️ DV — Discapacidad Visual'), ('DA', '👂 DA — Discapacidad Auditiva'), ('OTRO', '📋 Otro')], max_length=10)),
                ('nivel_apoyo', models.CharField(choices=[('leve', '🟢 Leve'), ('moderado', '🟡 Moderado'), ('severo', '🔴 Severo')], max_length=10)),
                ('fecha_ingreso', models.DateField()),
                ('diagnostico', models.TextField(verbose_name='Descripción del diagnóstico')),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pie', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Registro PIE',
                'verbose_name_plural': 'Registros PIE',
                'ordering': ['alumno__apellido'],
            },
        ),
        migrations.CreateModel(
            name='InformeAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('trimestre', models.CharField(choices=[('1', '1er Trimestre'), ('2', '2do Trimestre'), ('3', '3er Trimestre')], max_length=1)),
                ('logros', models.TextField(verbose_name='Logros del período')),
                ('dificultades', models.TextField(verbose_name='Dificultades observadas')),
                ('sugerencias', models.TextField(verbose_name='Sugerencias y próximos pasos')),
                ('para_apoderado', models.TextField(help_text='Texto en lenguaje simple para compartir con la familia', verbose_name='Mensaje para el apoderado')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pie.especialista')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='pie.registropie')),
            ],
            options={
                'verbose_name': 'Informe de Avance',
                'verbose_name_plural': 'Informes de Avance',
                'ordering': ['-anno', 'trimestre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prueba', '📝 Prueba Diferenciada'), ('trabajo', '📋 Trabajo Diferenciado'), ('oral', '🗣️ Evaluación Oral'), ('portafolio', '📁 Portafolio'), ('otro', '📌 Otro')], max_length=15)),
                ('asignatura', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('adecuaciones', models.TextField(help_text='Describe qué adecuaciones se realizaron para esta evaluación', verbose_name='Adecuaciones aplicadas')),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='pie.especialista')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='pie.registropie')),
            ],
            options={
                'verbose_name': 'Evaluación PIE',
                'verbose_name_plural': 'Evaluaciones PIE',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='especialista',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas', to='pie.registropie'),
        ),
        migrations.CreateModel(
            name='PACI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('trimestre', models.CharField(choices=[('1', '1er Trimestre'), ('2', '2do Trimestre'), ('3', '3er Trimestre')], max_length=1)),
                ('asignatura', models.CharField(max_length=100)),
                ('objetivo_general', models.TextField()),
                ('objetivos_especificos', models.TextField()),
                ('estrategias', models.TextField()),
                ('recursos', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacis', to='pie.registropie')),
            ],
            options={
                'verbose_name': 'PACI',
                'verbose_name_plural': 'PACIs',
                'ordering': ['-anno', 'trimestre'],
                'unique_together': {('registro', 'anno', 'trimestre', 'asignatura')},
            },
        ),
    ]
