# Generated by Django 6.0.2 on 2026-03-03 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('relacion', models.CharField(choices=[('padre', '👨 Padre'), ('madre', '👩 Madre'), ('tutor', '🧑 Tutor Legal'), ('abuelo', '👴 Abuelo/a'), ('otro', '👤 Otro')], default='padre', max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('datos_adicionales', models.TextField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MensajeApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('academico', '📚 Académico'), ('conductual', '⚠️ Conductual'), ('administrativo', '📋 Administrativo'), ('salud', '🏥 Salud'), ('otro', '💬 Otro')], default='academico', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('respondido', '✅ Respondido'), ('cerrado', '🔒 Cerrado')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='apoderados.apoderado')),
            ],
            options={
                'verbose_name': 'Mensaje de Apoderado',
                'verbose_name_plural': 'Mensajes de Apoderados',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
