# Generated by Django 4.2.29 on 2026-03-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('clase', '📘 Clase'), ('prueba', '📝 Prueba'), ('trabajo', '📋 Trabajo')], default='clase', max_length=10)),
                ('curso', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('unidad_tema', models.CharField(max_length=200)),
                ('objetivos', models.TextField()),
                ('actividades', models.TextField()),
                ('recursos', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', '✏️ Borrador'), ('publicada', '✅ Publicada'), ('finalizada', '🏁 Finalizada')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modified', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aviso', '📢 Aviso'), ('prueba', '📝 Recordatorio de Prueba'), ('trabajo', '📋 Recordatorio de Trabajo'), ('reunion', '👥 Reunión'), ('otro', '💬 Otro')], default='aviso', max_length=15)),
                ('curso', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('enviado_correo', models.BooleanField(default=False)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='mensajes_recibidos', to='alumnos.alumno')),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='planificaciones.planificacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_alumnos', to='profesores.profesor')),
            ],
            options={
                'verbose_name': 'Mensaje a Alumnos',
                'verbose_name_plural': 'Mensajes a Alumnos',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
